immich_api_key: "Z8eZKqSknH9AXlEj2xYCcHFJ2FFzkzgVMiowakEma8U"
immich_url: "localhost:2283"

disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)

show_time: true # true or false
time_format: 12 # 12 or 24

show_date: true # true or false
date_format: 02/01/2006 # 02 = day, 01 = month and 2006 = year e.g. 01/02/2006 for American format

refresh: 60 # in seconds

album: "" # ID of album to display

person: # ID(s) of person or people to display
  - ""

image_fit: contain # how the image fits the screen. Options are none, contain and cover

background_blur: true # display a blurred version of image as background

transition: none # cross-fade, fade or none

show_progress: false # display a progress bar

# Image METADATA
show_image_time: true # true or false
image_time_format: 12 # 12 or 24

show_image_date: true # true or false
image_date_format: 02/01/2006 # 02 = day, 01 = month and 2006 = year e.g. 01/02/2006 for American formate

# options that can not be changed via url params
kiosk:
  password: ""
